# Generated by Django 3.1.2 on 2020-11-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.PositiveBigIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=1024)),
                ('address', models.TextField()),
                ('main_phone', models.PositiveBigIntegerField()),
                ('mobile_phone', models.PositiveBigIntegerField()),
                ('checking_account', models.CharField(max_length=255)),
                ('mfo', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('oked', models.CharField(max_length=255)),
                ('head_manager', models.CharField(max_length=255)),
                ('head_account_manager', models.CharField(max_length=255)),
                ('released_by', models.CharField(max_length=255)),
                ('is_vat', models.BooleanField(default=False)),
                ('excise_tax', models.BooleanField(default=False)),
                ('sms_inform', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('unit', models.CharField(default='', max_length=50)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_vat', models.BooleanField(default=False)),
                ('vat_rate', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('vat_price', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveBigIntegerField(default=0)),
                ('invoice_date', models.DateTimeField()),
                ('contract_number', models.PositiveBigIntegerField(default=0)),
                ('contract_date', models.DateTimeField()),
                ('is_authorited', models.BooleanField(default=False)),
                ('authority_number', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('authority_date', models.DateTimeField(blank=True, null=True)),
                ('authorited_person', models.CharField(blank=True, max_length=255, null=True)),
                ('is_one_side_invoice', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/docs/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods', models.ManyToManyField(to='core.Good')),
                ('invoiced_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_from', to='core.company')),
                ('invoiced_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_to', to='core.company')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
        ),
    ]
