# Generated by Django 3.1.5 on 2021-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210107_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
