# Generated by Django 3.1.5 on 2021-01-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_language_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.partner'),
        ),
    ]
