# Generated by Django 3.1.5 on 2021-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_driver_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='login',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
