# Generated by Django 3.1.5 on 2021-01-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210108_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='devices',
            field=models.ManyToManyField(blank=True, to='core.Device'),
        ),
    ]
