# Generated by Django 3.1.5 on 2021-01-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210109_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='house',
            new_name='entrance',
        ),
    ]
